jobs:
  include:
    - language: node_js
      node_js: 12
      if: branch = master
      script:
        - cd baseclient/ts
        - npm install
        - npm run test-cov
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF node_js
    - language: java
      jdk: openjdk8
      if: branch = master
      script:
        - cd baseclient/java
        - mvn test -B
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF java
    - language: go
      go: 1.12.x
      if: branch = master
      script:
        - cd baseclient/go
        - export GO111MODULE=on
        - go mod tidy
        - go test -race -coverprofile=coverage.txt -covermode=atomic ./service/... ./utils...
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF go
    - language: csharp
      sudo: true
      mono: none
      dotnet: 2.2
      dist: xenial
      if: branch = master
      before_install:
      - if [ $TRAVIS_OS_NAME == "linux" ]; then
          export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
          Xvfb :99 &
          sleep 3;
        fi
      - dpkg --compare-versions `npm -v` ge 6.7 || npm i -g npm@^6.7
      - wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
      - sudo dpkg -i packages-microsoft-prod.deb
      - sudo apt-get install apt-transport-https
      - sudo apt-get update
      - sudo apt-get install dotnet-sdk-2.2
      - sudo apt install xvfb
      install:
        - cd baseclient/csharp/unitTest
        - dotnet tool install --global altcover.visualizer
        - dotnet restore
        - dotnet build
        - cd ../
      script:
        - dotnet test unitTest/ /p:AltCover=true
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF csharp