
jobs:
  include:
    - language: node_js
      node_js: 12
      script:
        - cd baseclient/ts
        - npm install
        - npm run ci

    - language: java
      jdk: openjdk8
      script:
        - cd baseclient/java
        - mvn test -B
