jobs:
  include:
    - language: node_js
      node_js: 12
      script:
        - cd baseclient/ts
        - npm install
        - npm run ci
    - language: java
      jdk: openjdk8
      if: branch = master
      script:
        - cd baseclient/java
        - mvn test -B
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF java
    - language: go
      go: 1.12.x
      script:
        - cd baseclient/go
        - export GO111MODULE=on
        - go mod tidy
        - go test -race -coverprofile=coverage.txt -covermode=atomic ./service/... ./utils...
    - language: csharp
      sudo: true
      mono: none
      dotnet: 2.2
      dist: xenial
      branches:
        only:
          - master
      install:
        - cd baseclient/csharp/unitTests
        - dotnet tool install --global altcover.visualizer
        - dotnet restore
        - dotnet build
        - cd ../
      script:
        - dotnet test unitTests/ /p:AltCover=true
      after_success:
        - bash <(curl -s https://codecov.io/bash)
