all:

install:
	# Install dependencies for C#
	# ...
	# Install dependencies for Go
	# ...
	# Install dependencies for Java
	# ...
	# Install dependencies for TypeScript
	# ...

test:
	# Run baseclient test cases for C#
	# ...
	# Run baseclient test cases for Go
	# ...
	# Run baseclient test cases for Java
	# ...
	# Run baseclient test cases for TypeScript
	# ...
